version: '3.9'

services:
  vpn:
    build: https://github.com/wfg/docker-openvpn-client.git
    container_name: ripper-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - HTTP_PROXY=off
      - SOCKS_PROXY=off
    volumes:
      - ./vpn:/data/vpn
    restart: unless-stopped

  ripper:
    build: .
    depends_on:
      - "vpn"
    container_name: ripper-script
    network_mode: "service:vpn"
    restart: unless-stopped
    command: www.rt.com

  autoheal:
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped


